apiVersion: apps/v1
kind: Deployment
metadata:
  name: smokepinger
  labels:
    app: smokeping
spec:
  selector:
    matchLabels:
      app: smokeping
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: smokeping        
    spec:
      containers:
        - name: smokepinger
          image: home-smokeping
          ports:
            - name: web
              containerPort: 80
              protocol: TCP